name: Debug Linux via Tailscale
on: [ workflow_dispatch ]   # Workflow is triggered manually

jobs:
  tailscale-debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      # Connect runner to your Tailnet:
      - name: Connect to Tailscale
        uses: tailscale/github-action@v4
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}

      # Enable Tailscale SSH daemon:
      - name: Enable Tailscale SSH
        run: |
          sudo tailscale set --ssh

          echo "==========================================================="
          echo "Tailscale IPs: $(tailscale ip | xargs)"
          echo "Connect via SSH using:"
          echo "  * ssh runner@$(tailscale ip -4)"
          echo "  * ssh runner@$(tailscale ip -6)"
          echo "==========================================================="

      # Pre-install Linux APT packages:
      - name: Install custom packages
        run: |
          sudo apt-get update
          sudo apt install -y bash-completion build-essential cmake gettext git joe sudo

          sudo apt install -y libmaxminddb-dev

          sudo apt install -y libbz2-dev libsctp-dev ghostscript graphicsmagick pdf2svg

          sudo apt install -y bison flex libcurl4-openssl-dev libssl-dev

          sudo apt install -y libboost-all-dev liblzma-dev
          sudo apt install -y libmariadb-dev libpqxx-dev libmongoc-dev libbson-dev

          sudo apt install -y qt6-base-dev qt6-tools-dev

          sudo apt install -y gimp libimage-exiftool-perl
          sudo apt install -y fonts-noto

          sudo apt install -y gnutls-bin libnss3-tools

          sudo apt install -y autoconf automake libglib2.0-dev libtool

          sudo apt install -y libpulse-dev

          sudo apt install -y libssl-dev libjansson-dev libldns-dev libmnl-dev libuv1-dev

          sudo apt install -y libgraphicsmagick1-dev

          sudo apt install -y python3 python3-venv python3-distro python3-psutil
          python3 -m venv ~/venv
          . ~/venv/bin/activate
          pip install distro psutil

      # Clone repositories:
      - name: Clone repositories
        run: |
          mkdir -p ~/src && cd ~/src
          git clone https://dreibh@github.com/dreibh/bibtexconv
          git clone https://dreibh@github.com/simula/dynmhs
          # git clone https://dreibh@github.com/dreibh/fractgen
          # git clone https://dreibh@github.com/dreibh/hipercontracer
          # git clone https://dreibh@github.com/dreibh/netperfmeter
          # git clone https://dreibh@github.com/dreibh/rserpooldemo
          # git clone https://dreibh@github.com/dreibh/rsplib
          # git clone https://dreibh@github.com/dreibh/rtpaudio
          # git clone https://dreibh@github.com/dreibh/sctplib
          # git clone https://dreibh@github.com/dreibh/slideshow
          # git clone https://dreibh@github.com/dreibh/socketapi
          # git clone https://dreibh@github.com/dreibh/subnetcalc
          git clone https://dreibh@github.com/dreibh/system-tools
          # git clone https://dreibh@github.com/dreibh/tsctp
          git clone https://dreibh@github.com/simula/nornet-vmimage-builder-scripts.git vmimage-builder-scripts

      # Install System-Tools and configure environment:
      - name: Install System-Tools and configure environment
        run: |
          cd ~/src/system-tools
          ./autogen.sh
          sudo make install

          sudo mkdir -p /usr/local/etc/system-info.d/
          sudo cp \
             ~/src/vmimage-builder-scripts/files/11-system-info.files/01-hostname \
             ~/src/vmimage-builder-scripts/files/80-simulamet.files/02-simulamet \
             /usr/local/etc/system-info.d/

          # Set shell to Bash:
          sudo chsh -s /bin/bash runner

          # Enable Bash shell completions:
          cat >>~/.bashrc <<'EOF'
          [[ -r "/usr/share/bash-completion/bash_completion" ]] && . "/usr/share/bash-completion/bash_completion"
          EOF
          cat ~/src/vmimage-builder-scripts/files/05-user-settings.files/bashrc >>~/.bashrc

          # Set a useful hostname:
          sudo Reset-Machine-ID --yes-to-all-i-am-really-sure -MSK -H "linux.github.test"

      # Pause the runner for interactive SSH debugging:
      - name: Wait for SSH debugging
        run: |
          while true; do
            echo "==========================================================="
            echo "Tailscale IPs: $(tailscale ip | xargs)"
            echo "Connect via SSH using:"
            echo "  * ssh runner@$(tailscale ip -4)"
            echo "  * ssh runner@$(tailscale ip -6)"
            echo "==========================================================="
            sleep 60
          done
