name: Debug Windows via Tailscale
on: [ workflow_dispatch ]   # Workflow is triggered manually

jobs:
  tailscale-debug:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash   # Use Git Bash for command compatibility across steps

    steps:
      - uses: actions/checkout@v7

      # Connect runner to your Tailnet:
      - name: Connect to Tailscale
        uses: tailscale/github-action@v4
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}

      # Enable Tailscale SSH daemon:
      - name: Enable Tailscale SSH
        run: |
          tailscale set --ssh

          echo "==========================================================="
          echo "Tailscale IPs: $(tailscale ip | xargs)"
          echo "Connect via SSH using:"
          echo "  * ssh runneradmin@$(tailscale ip -4)"
          echo "  * ssh runneradmin@$(tailscale ip -6)"
          echo "==========================================================="

      # Pre-install Windows packages via Chocolatey and Pip:
      - name: Install custom packages
        run: |
          choco install -y cmake wget ghostscript graphicsmagick exiftool gimp python3

          python -m pip install --upgrade pip
          pip install distro psutil

          python -m venv ~/venv
          source ~/venv/Scripts/activate
          pip install distro psutil

      # Clone repositories:
      - name: Clone repositories
        run: |
          mkdir -p ~/src && cd ~/src
          git clone https://dreibh@github.com/dreibh/bibtexconv
          git clone https://dreibh@github.com/dreibh/fractgen
          git clone https://dreibh@github.com/dreibh/hipercontracer
          git clone https://dreibh@github.com/dreibh/netperfmeter
          git clone https://dreibh@github.com/dreibh/rserpooldemo
          git clone https://dreibh@github.com/dreibh/rsplib
          git clone https://dreibh@github.com/dreibh/rtpaudio
          git clone https://dreibh@github.com/dreibh/sctplib
          git clone https://dreibh@github.com/dreibh/slideshow
          git clone https://dreibh@github.com/dreibh/socketapi
          git clone https://dreibh@github.com/dreibh/subnetcalc
          git clone https://dreibh@github.com/dreibh/system-tools
          git clone https://dreibh@github.com/dreibh/tsctp
          git clone https://dreibh@github.com/simula/nornet-vmimage-builder-scripts.git vmimage-builder-scripts

      # Configure environment:
      - name: Configure environment
        run: |
          mkdir -p /c/usr/local/etc/system-info.d/
          cp \
             ~/src/vmimage-builder-scripts/files/11-system-info.files/01-hostname \
             ~/src/vmimage-builder-scripts/files/80-simulamet.files/02-simulamet \
             /c/usr/local/etc/system-info.d/ || true

          # Apply Bash configuration settings:
          cat ~/src/vmimage-builder-scripts/files/05-user-settings.files/bashrc >>~/.bashrc || true

      # Pause the runner for interactive SSH debugging:
      - name: Wait for SSH debugging
        run: |
          while true; do
            echo "==========================================================="
            echo "Tailscale IPs: $(tailscale ip | xargs)"
            echo "Connect via SSH using:"
            echo "  * ssh runneradmin@$(tailscale ip -4)"
            echo "  * ssh runneradmin@$(tailscale ip -6)"
            echo "==========================================================="
            sleep 60
          done
